Add ID Token to Scope and Store in Storage
udplabs/udp-mobile pull request #14
Opened 2021-08-19 17:01 UTC by brh55

Per #2 , We need this to demonstrate ID Token functionality and streamline profile data.

2021-08-19 17:20 UTC, noinarisak requested changes
We should remove commented out code. ;)

2021-08-19 17:20 UTC, noinarisak commented on src/screens/LoginScreen.js
>      //const uri = `${config.authUri}?client_id=${config.clientId}&response_type=token&scope=openid&redirect_uri=${config.authUri}/callback&state=customstate&nonce=${config.nonce}`;
Remove comment out code. 😄

2021-08-19 17:38 UTC, brh55 commented on src/screens/LoginScreen.js
>      //const uri = `${config.authUri}?client_id=${config.clientId}&response_type=token&scope=openid&redirect_uri=${config.authUri}/callback&state=customstate&nonce=${config.nonce}`;
Haha there is a few stray comment codes

2021-08-20 18:01 UTC, noinarisak approved these changes

2021-08-20 18:02 UTC, merged